# services/user-service/Dockerfile.dev

# Ten obraz będzie zawierał wszystkie zależności, w tym pytest
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Domyślna komenda, która uruchomi testy
CMD ["pytest"]